In [5]:
import numpy as np

In [6]:
a = []
size = int(input("enter total elemenets:"))
for i in range(size):
    val= int(input("enter numer:"))
    a.append(val)
b = np.array(a)
b

enter total elemenets:3
enter numer:45
enter numer:56
enter numer:78


array([45, 56, 78])

pre-define function

In [ ]:
#Matrix --> rows , columns
#Matrix ---> n(r) = n(c) ---> symmmatric matrix,
# n(r)!=n(c)---> Asymmatric matrix
#diagnol positional elements = [(1,1),(2,2),(3,3),....(n,n)]

In [ ]:
#(1.)  zeros() ---> IT will create an array in which all the values eill be 0.

In [7]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [9]:
a = np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#(2.) ones()  ---> It will create an array in which all the values will bw 1.

In [10]:
b = np.ones(4)
b

array([1., 1., 1., 1.])

In [12]:
c = np.ones((3,5))
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#(3.) eye()  ----> It will create an array in which diagonal posiitin element wil be 1
# and rest all will be 0.

In [13]:
d = np.eye(3,3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
e = np.eye(3,5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
# diag() ---> It will create an array in which we can out custom digonal values

In [16]:
f = np.array([2,2,2,22,2,2,2])
g = np.diag(f)
g

array([[ 2,  0,  0,  0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0],
       [ 0,  0,  0, 22,  0,  0,  0],
       [ 0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  2,  0],
       [ 0,  0,  0,  0,  0,  0,  2]])

In [18]:
h = np.array([2,34,54,22,13,89,2])
i = np.diag(h)
i

array([[ 2,  0,  0,  0,  0,  0,  0],
       [ 0, 34,  0,  0,  0,  0,  0],
       [ 0,  0, 54,  0,  0,  0,  0],
       [ 0,  0,  0, 22,  0,  0,  0],
       [ 0,  0,  0,  0, 13,  0,  0],
       [ 0,  0,  0,  0,  0, 89,  0],
       [ 0,  0,  0,  0,  0,  0,  2]])

In [ ]:
#(5.)  Random ---->
#(a.) RAndiant()  ---> It eill generate random numbers in a given range.
#syntax: np.random.randint(min_number , max_number , total_numbers)

#(b.) Rand()  ---> it will generate random numbers from 0 to 1.
#syntax : np.random.rand(tatal_numbers)  #0 to 1 range by default.

In [19]:
a = np.random.randint(1,10,4)
a

array([9, 1, 8, 5])

In [21]:
b = np.random.rand(5) #generate 0 to 1 range bydefault.
b

array([0.3499993 , 0.67864135, 0.66331481, 0.25419187, 0.41758771])